catalogo/urls.py
from django.urls import path
from .views import index, RegistroUsuario, clientecrear,clientelist,ordencrear,success
from . import views

app_name="apps"
urlpatterns = [
    path('', index,name='index'),
	path('clientenew/', clientecrear,name='nuevocliente'),
	path('clientelist',clientelist,name='listacliente'),
	path('registrar/', RegistroUsuario.as_view(),name='registrar'),
	path('crearorden/',ordencrear,name='crearorden'),
	path('success/', success, name='success'),
	path(r'^delete/(?P<pk>\d+)/$', views.DeleteCliente.as_view(), name='delete'),
	path('ingreso/', views.ingreso, name='ingreso'),
]

sitio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.views import LoginView 
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalogo/',include('catalogo.urls',namespace='catalogo')),
    url(r'', include('catalogo.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
]

catalogo/models.py
from django.db import models

class Cliente(models.Model):
	nombre = models.CharField(max_length=40)
	direccion = models.CharField(max_length=70)
	ciudad = models.CharField(max_length=30)
	comuna = models.CharField(max_length=30)
	telefono = models.CharField(max_length=10)
	email = models.EmailField(max_length=50)

	def __str__(self):
		return self.nombre

class Orden(models.Model):
	folio = models.AutoField(primary_key=True)
	cliente = models.ForeignKey('Cliente',db_column='nombre', on_delete=models.CASCADE)
	fecha = models.DateField()
	horainicio = models.TimeField()
	horafin = models.TimeField()
	idascensor = models.IntegerField()
	modeloasc = models.CharField(max_length=30)
	fallas = models.CharField(max_length=200, blank=True, null=True)
	reparaciones = models.CharField(max_length=200, blank=True, null=True)
	piezascambiadas = models.CharField(max_length=100, blank=True, null=True)
	receptor = models.CharField(max_length=50)
	tecnico = models.ForeignKey('tecnico', on_delete=models.CASCADE)

class tecnico(models.Model):
	name = models.CharField(max_length=30)

	def __str__(self):
		return self.name

catalogo/forms.py
from django import forms

from .models import Cliente, Orden
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class ClienteForm(forms.ModelForm):

	class Meta:
		model = Cliente

		fields = [
			'nombre',
			'direccion',
			'ciudad',
			'comuna',
			'email',
			'telefono',
		]
		labels = {
			'nombre': 'Nombre',
			'direccion': 'Direccion',
			'ciudad': 'Ciudad',
			'comuna': 'Comuna',
			'email': 'Email',
			'telefono': 'Telefono',
		}
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'direccion': forms.TextInput(attrs={'class':'form-control'}),
			'ciudad': forms.TextInput(attrs={'class':'form-control'}),
			'comuna': forms.TextInput(attrs={'class':'form-control'}),
			'email': forms.TextInput(attrs={'class':'form-control','type':'email'}),
			'telefono': forms.TextInput(attrs={'class':'form-control','type':'number'}),

		}
class OrdenForm(forms.ModelForm):
	class Meta:

		model = Orden
		fields =[
			'cliente',
			'fecha',
			'horainicio',
			'horafin',
			'idascensor',
			'modeloasc',
			'fallas',
			'reparaciones',
			'piezascambiadas',
			'receptor',
			'tecnico',
		]
		labels = {
			'cliente': 'Cliente Asociado',
			'fecha': 'Fecha de Trabajo',
			'horainicio': 'Hora de Inicio',
			'horafin': 'Hora de Fin',
			'idascensor': 'Código de Ascensor',
			'modeloasc': 'Modelo ',
			'fallas': 'Fallas detectadas',
			'reparaciones': 'Reparaciones realizadas',
			'piezascambiadas': 'Piezas reemplazadas',
			'receptor': 'Receptor de trabajo',
			'tecnico': 'Tecnico encargado',
		}
		widgets = {
			'cliente': forms.Select(attrs={'class': 'form-control col-12 justify-content-center'	}),
			'fecha': forms.SelectDateWidget(attrs={'class':'form-control col-12 justify-content-center'}),
			'horainicio': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center','type':'time'}),
			'horafin': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center' ,'type':'time'}),
			'idascensor': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center','type':'number'}),
			'modeloasc': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center'}),
			'fallas': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center' }),
			'reparaciones': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center'}),
			'piezascambiadas': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center'}),
			'receptor': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center'}),
			'tecnico': forms.Select(attrs={'class': 'form-control col-12 justify-content-center'}),
		}

class RegistroForm(UserCreationForm):

	class Meta:
		model = User

		fields = [
				'username',
				'first_name',
				'last_name',
				'email',
			]
		help_texts={
				'username': None,
		}
		#no olivdar poner clases para asignar un nuevo diseño, usar el de widgets 
		labels = {
				'username': 'Nombre de Usuario',
				'first_name': 'Nombres',
				'last_name': 'Apellidos',
				'email': 'Correo Electronico',
		}

catalogo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ClienteForm, OrdenForm
from .models import Cliente
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy, reverse
from .forms import RegistroForm
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response


def index(request):
	return render(request,"index.html")

def clientecrear(request):
	if request.method =='POST':
		form = ClienteForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('catalogo:success')
	else:
		form = ClienteForm()

		return render(request,'clienteform.html',{'form':form})

def ingreso(request):
	return render(request,'login.html')

def clientelist(request):
	cliente = Cliente.objects.all()
	contexto = {'clientes':cliente}
	return render(request, 'clientelist.html',contexto)

class RegistroUsuario(CreateView):
	model = User
	template_name = "registro.html"
	form_class = RegistroForm
	success_url = reverse_lazy('catalogo:index')

def ordencrear(request):
	if request.method =='POST':
		form = OrdenForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('catalogo:success')
	else:
		form = OrdenForm()

		return render(request,'ordenform.html',{'form':form})

def success(request):
    return render(request,'success.html')

class DeleteCliente(DeleteView):
	model = Cliente
	template_name = "registro/deletecliente.html"
	# success_url = reverse_lazy('catalogo:listacliente') error aca eliminar 

class UpdateCliente(UpdateView):
	model = Cliente
	fields = ['nombre','direction','ciudad','comuna','telefono','email']

catalogo/templates/base.html
{% load staticfiles %}
{% load bootstrap4 %}
{% bootstrap_css %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device=width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <title>Manteminiento de Ascensores</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <script src="{% static 'js/comunas.js'%}"></script>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}" type="text/css">
</head>
<body>
 
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'catalogo:index' %}">Inicio</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'catalogo:nuevocliente' %}">Agregar Cliente</a>
              </li>
            <li>
              <a class="nav-link" href="{% url 'catalogo:delete' %}">Eliminar Cliente</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'catalogo:listacliente' %}">Lista de Clientes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'catalogo:crearorden' %}">Agendar Orden</a>
            </li>
          </ul>
     </nav>                 
     <div class="container">   
    <div class="row">
      <div class="col-sm-4 col-md-6 col-xl-12 text-center">
      <h1 class=text-center></h1>
      </div>
    </div>
   
    <div class="row">
      <div class="col-sm-4 col-md-6 col-xl-12 text-center">           
               {% block contenido %}
               
               {% endblock %}
      </div>

    </div>
  </div>
          
          
    
        
</body>
</html>

catalogo/templates/clienteform.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
<form method="post">
  {% csrf_token %}
  <table></table>
  {{ form.as_p }}
  <button type="submit" class="btn">Guardar</button>
</form>
{% endblock %}

catalogo/templates/clientelist.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
<table class=table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Direccion</td>
			<td>Ciudad</td>
			<td>Comuna</td>
			<td>Telefono</td>
			<td>Email</td>
		</tr>

	</thead>
	<tbody>
		{% if clientes %}
		{% for cliente in clientes %}

		<tr>
			<td>{{ cliente.id }}</td>
			<td>{{ cliente.nombre }}</td>
			<td>{{ cliente.direccion }}</td>
			<td>{{ cliente.ciudad }}</td>
			<td>{{ cliente.comuna }}</td>
			<td>{{ cliente.telefono }}</td>
			<td>{{ cliente.email }}</td>
			

		</tr>
		{% endfor %}
		{% else %}
		<h1> No hay registros de clientes</h1>

		{% endif %}
	</tbody>
{% endblock %}

catalogo/templates/deletecliente.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block content %}

<h1>Eliminar Cliente</h1>
<p>¿estas seguro(a) que quieres eliminar al cliente {{ object.name }}</p> 

<form actiom="" method ="POST">
{% csrf_token %}
<input type="submit" action="" value="Eliminar"/>
</from>
{% endblock %}

catalogo/templates/index.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
<p>BIENVENIDO</p>

<a href="{% url 'login' %}"> LOGIN</a>


{% endblock %}

catalogo/templates/login.html
{%extends 'base.html'%}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <link rel="stylesheet" href="estilos.css" />
  <title>jQuery Example</title>
  <script>
    $(document).ready(function() {
      // Execute some code here
    });
  </script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.2&appId=2262328720717911';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="container">
	


	<div class="row justify-content-center"> 
	
		<h3>Inicio de Sesión</h3>
	</div>
	<div class="d-flex justify-content-center">
	<form method="post">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<label for="username">Usuario:</label>
					<input class="form-control" type="text" name="username">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<label for="username">Contraseña:</label>
					<input class="form-control" type="password" name="password">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<input class="btn btn-primary" type="submit" value="Ingresar">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<a href="{% url 'ascensor:registrar' %}">Registrar</a>
				</div>	
			</div>
		</div>
		<div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
		

	</form>
	</div>
	</div>
{% endblock %}

catalogo/templates/ordenform.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn">Guardar</button>
</form>
{% endblock %}

catalogo/templates/registo/deletecliente.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}

{% block content %}

<h1>Eliminar Cliente</h1>
<p>¿estas seguro(a) que quieres eliminar al cliente {{ cliente}}</p> 

<form actiom="" method ="POST">
{% csrf_token %}
<input type="submit" action="" value="Eliminar"/>
</from>
{% endblock %}

catalogo/templates/registo/login.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <link rel="stylesheet" href="estilos.css" />
  <title>jQuery Example</title>
  <script>
    $(document).ready(function() {
      // Execute some code here
    });
  </script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.2&appId=2262328720717911';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="container">
	


	<div class="row justify-content-center"> 
	
		<h3>Inicio de Sesión</h3>
	</div>
	<div class="d-flex justify-content-center">
	<form method="post">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<label for="username">Usuario:</label>
					<input class="form-control" type="text" name="username">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<label for="username">Contraseña:</label>
					<input class="form-control" type="password" name="password">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<input class="btn btn-primary" type="submit" value="Ingresar">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<a href="{% url 'ascensor:registrar' %}">Registrar</a>
				</div>	
			</div>
		</div>
		<div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
		

	</form>
	</div>
	</div>
{% endblock %}

catalogo/templates/registro.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}

<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn">Guardar</button>

</form>

{% endblock %}

catalogo/templates/success.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
<br>
<br>
<br>
<br>
<br>
<br>

<h2">Formulario enviado de manera exitosa</h2>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device=width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <title>Manteminiento de Ascensores</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <script src="{% static 'js/comunas.js'%}"></script>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}" type="text/css">
</head>
<body>
 
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'catalogo:index' %}">Inicio</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'catalogo:nuevocliente' %}">Agregar Cliente</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'catalogo:listacliente' %}">Lista de Clientes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'catalogo:crearorden' %}">Agendar Orden</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'catalogo:registrar' %}">Registrar</a>
            </li>

          </ul>
     </nav>                 
     <div class="container">   
    <div class="row">
      <div class="col-sm-4 col-md-6 col-xl-12 text-center">
      <h1 class=text-center></h1>
      </div>
    </div>
   
    <div class="row">
      <div class="col-sm-4 col-md-6 col-xl-12 text-center">           
               {% block contenido %}
               
               {% endblock %}
      </div>

    </div>
  </div>
          
          
    
        
</body>
</html>

templates/clienteform.html
{%extends 'base.html'%}
{%block contenido %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
<form method="post">
  {% csrf_token %}
  <table></table>
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/clientelist.html
{%extends 'base.html'%}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
<table class=table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Direccion</td>
			<td>Ciudad</td>
			<td>Comuna</td>
			<td>Telefono</td>
			<td>Email</td>

		</tr>

	</thead>
	<tbody>
		{% if clientes %}
		{% for cliente in clientes %}

			<tr>
				<td>{{ cliente.id }}</td>
				<td>{{ cliente.nombre }}</td>
				<td>{{ cliente.direccion }}</td>
				<td>{{ cliente.ciudad }}</td>
				<td>{{ cliente.comuna }}</td>
				<td>{{ cliente.telefono }}</td>
				<td>{{ cliente.email }}</td>
			</tr>
		{% endfor %}
		{% else %}
		<h1> No hay registros de clientes</h1>

		{% endif %}
	</tbody>
{% endblock %}

templates/deletecliente.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block content %}

<h1>Eliminar Cliente</h1>
<p>¿estas seguro(a) que quieres eliminar al cliente {{ object.name }}</p> 

<form actiom="" method ="POST">
{% csrf_token %}
<input type="submit" action="" value="Eliminar"/>
</from>
{% endblock %}

templates/index.html
{%extends 'base.html'%}
{%block contenido %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
<p>BIENVENIDO</p>

<a href="{% url 'login' %}"> LOGIN</a>


{% endblock %}

templates/login.html
{%extends 'base.html'%}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <link rel="stylesheet" href="estilos.css" />
  <title>jQuery Example</title>
  <script>
    $(document).ready(function() {
      // Execute some code here
    });
  </script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.2&appId=2262328720717911';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="container">
	


	<div class="row justify-content-center"> 
	
		<h3>Inicio de Sesión</h3>
	</div>
	<div class="d-flex justify-content-center">
	<form method="post">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<label for="username">Usuario:</label>
					<input class="form-control" type="text" name="username">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<label for="username">Contraseña:</label>
					<input class="form-control" type="password" name="password">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<input class="btn btn-primary" type="submit" value="Ingresar">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<a href="{% url 'ascensor:registrar' %}">Registrar</a>
				</div>	
			</div>
		</div>
		<div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
		

	</form>
	</div>
	</div>
{% endblock %}

templates/ordenform.html
{%extends 'base.html'%}
{%block contenido %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/registo/deletecliente.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block content %}

<h1>Eliminar Cliente</h1>
<p>¿estas seguro(a) que quieres eliminar al cliente {{ object.name }}</p> 

<form actiom="" method ="POST">
{% csrf_token %}
<input type="submit" action="" value="Eliminar"/>
</from>
{% endblock %}

templates/registo/login.html
{%extends 'base.html'%}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{%block contenido %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <link rel="stylesheet" href="estilos.css" />
  <title>jQuery Example</title>
  <script>
    $(document).ready(function() {
      // Execute some code here
    });
  </script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.2&appId=2262328720717911';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="container">
	


	<div class="row justify-content-center"> 
	
		<h3>Inicio de Sesión</h3>
	</div>
	<div class="d-flex justify-content-center">
	<form method="post">
	{% csrf_token %}
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<label for="username">Usuario:</label>
					<input class="form-control" type="text" name="username">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<label for="username">Contraseña:</label>
					<input class="form-control" type="password" name="password">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<input class="btn btn-primary" type="submit" value="Ingresar">
				</div>	
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3 col-xl-12">
				<div class="form-group">
					<a href="{% url 'ascensor:registrar' %}">Registrar</a>
				</div>	
			</div>
		</div>
		<div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
		

	</form>
	</div>
	</div>
{% endblock %}

templates/registro.html
{%extends 'base.html'%}
{%block contenido %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}

<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Guardar</button>

</form>

{% endblock %}

templates/success.html
{%extends 'base.html'%}
{%block contenido %}
<br>
<br>
<br>
<br>
<br>
<br>

<h2">Formulario enviado de manera exitosa</h2>
{% endblock %}